# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99451d3de2511d40d9b9fdb04542a48ec52f0d96c62bd896ec1826c5bb3f13068d454954bf531bf60136cb163bdd108771000a9fadb242e17097ffec7c963f10

test:
  secret_key_base: c89ad0b4e2e54143e8b18c293bbb1507cb4e72a17a94dccdcd635ec086879cf4d56430fc77c40854983773ac5f596cb97e64ec543765daf73b1f4cf5d780976a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
